---
- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
    owner: dockremap
    group: docker
    recurse: true
  with_items:
    - '{{ status_go_node_cont_vol }}/keys'
    - '{{ status_go_node_cont_vol }}/data'
    - '{{ status_go_node_cont_vol }}/conf'

- name: Create database directories
  file:
    path: '{{ item }}'
    owner: '{{ status_go_db_host_uid }}'
    group: 'dockremap'
    mode: 0777
    state: 'directory'
  with_items:
    - '{{ status_go_db_cont_vol }}/data'
    - '{{ status_go_db_cont_vol }}/backup'

- name: Create config file
  template:
    src: 'config.json.j2'
    dest: '{{ status_go_node_cont_vol }}/conf/config.json'
    owner: dockremap
    group: docker
    mode: 0640
  register: status_go_config_file

- name: Create wrapper scripts
  template:
    src: '{{ item }}.j2'
    dest: '{{ status_go_service_path }}/{{ item }}'
    owner: dockremap
    group: docker
    mode: 0755
  with_items:
    - 'rpc.sh'
    - 'psql.sh'
