---
- name: Create database directories
  file:
    path: '{{ item }}'
    owner: '{{ status_go_db_host_uid }}'
    group: 'dockremap'
    mode: 0777
    state: 'directory'
  with_items:
    - '{{ status_go_db_cont_vol }}/data'
    - '{{ status_go_db_cont_vol }}/backup'

- name: Create config file
  template:
    src: 'config.json.j2'
    dest: '{{ status_go_node_cont_vol }}/conf/config.json'
    owner: dockremap
    group: docker
    mode: 0640
  register: status_go_config_file

- name: Create script for calling RPC endpoint
  template:
    src: 'rpc.sh.j2'
    dest: '{{ status_go_service_path }}/rpc.sh'
    owner: dockremap
    group: docker
    mode: 0755

- name: Create script for using Postgres client
  template:
    src: 'psql.sh.j2'
    dest: '{{ status_go_service_path }}/psql.sh'
    owner: dockremap
    group: docker
    mode: 0755
