---
- name: Create directories
  file:
    path:    '{{ item.path }}'
    mode:    '{{ item.mode }}'
    state:   'directory'
    owner:   'dockremap'
    group:   'docker'
    recurse: true
  with_items:
    - { path: '{{ status_go_node_cont_vol }}/keys', mode: '0755' }
    - { path: '{{ status_go_node_cont_vol }}/conf', mode: '0755' }
    - { path: '{{ status_go_node_cont_vol }}/data', mode: '0750' }

- name: Create database directories
  when: status_go_db_backup_enabled
  file:
    path:  '{{ item }}'
    owner: '{{ status_go_db_host_uid }}'
    group: 'dockremap'
    state: 'directory'
    mode:  0777
  with_items:
    - '{{ status_go_db_cont_vol }}/data'
    - '{{ status_go_db_cont_vol }}/backup'

- name: Create config file
  template:
    src:   'config.json.j2'
    dest:  '{{ status_go_node_cont_vol }}/conf/config.json'
    owner: 'dockremap'
    group: 'docker'
    mode:  0640
  register: status_go_config_file

- name: Create RPC wrapper script
  template:
    src:   'rpc.sh.j2'
    dest:  '{{ status_go_service_path }}/rpc.sh'
    owner: 'dockremap'
    group: 'docker'
    mode:  0755
