---
- name: Create compose file
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ status_go_service_compose }}'
    owner: 'dockremap'
    group: 'docker'
    mode: 0640

- name: Create containers
  docker_compose:
    project_src: '{{ status_go_service_path }}'
    pull: true
    build: false
    state: '{{ compose_state }}'
    restarted: '{{ compose_restart }}'
    recreate: |-
      {{ ( status_go_config_file.changed or
           status_go_key_file.changed )
      | ternary("always", compose_recreate) }}
